### ISSUE TITLE
List not parsing

### ISSUE THREAD

**Issue by stevepeak** [microservices/omg-cli#153]
```yaml
actions:
  go:
    arguments:
      this:
        type: list
```

```
omg exec go -a 'this=[1]'
✖ Failed action: `go`: Argument: `this` must be of type: `list`
```

**Comment by TomPed** [comment]
@stevepeak what version `omg` are you running? This works fine in my side:
```yml
omg: 1

actions:
  exec:
    help: A sample action that interfaces via docker exec
    output:
      type: map
    format:
      command: ['node', 'exec.js']
    arguments:
      x:
        type: int
        required: true
      y:
        type: int
        default: 0
      z:
        type: int
      this:
        type: list
```

```sh
~/test-service (master|✚1) $ omg run exec -a x=1 -a y=2 -a z=2 -a 'this=[3]' -e one=one
ℹ Building Docker image
Sending build context to Docker daemon  103.4kB
Step 1/4 : FROM node:alpine
 ---> 1959078abed4
Step 2/4 : RUN npm install request
 ---> Using cache
 ---> 4fc4a00a9b7b
Step 3/4 : COPY exec.js /exec.js
 ---> Using cache
 ---> 620aecd6eba7
Step 4/4 : COPY server.js /server.js
 ---> Using cache
 ---> a134c46750c9
Successfully built a134c46750c9
Successfully tagged omg/tomped/test-service:latest
✔ Built Docker image with name: omg/tomped/test-service
✔ Started Docker container: 9698d7dac3a3
✔ Health check passed
✔ Ran action: `exec` with output: {
  "sum": 5,
  "args": {
    "x": 1,
    "y": 2,
    "z": 2,
    "this": [
      3
    ]
  },
  "environment_variables": {
    "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "HOSTNAME": "9698d7dac3a3",
    "one": "one",
    "two": "two",
    "NODE_VERSION": "11.7.0",
    "YARN_VERSION": "1.13.0",
    "HOME": "/root"
  }
}
✔ Stopped Docker container: 9698d7dac3a3
```
