### ISSUE TITLE
Add support for event and pubsub

### ISSUE THREAD

**Issue by stevepeak** [microservices/omg-cli#38]
Services may act as a pubsub or filter specific events. Let's start with the following three examples.

### Examples

<details>
<summary>GitHub Webhooks</summary>

```coffee
github webhooks as client
```
> ```sh
> docker run -d -e OMG_ENDPOINT=platform --entrypoint ./start github
> ```

> Publish Event
> ```js
> POST <platform> {
>   "objectId": null,
>   "event": "push",
>   "data": {
>     ...
>   }
> }
> ```

```coffee
  when client push as payload
    # do stuff with the payload from GitHub
```

----

```yaml
# microservice.yml
commands:
  webhooks:
    events:
      push:
    	output:
          type: map
    run:
      command: ["./start"]
```

</details>
<details>
<summary>Slack Bot</summary>

```coffee
slack bot as client
```
> Start the service
> ```sh
> docker run -d --entrypoint ./start slack
> ```
```coffee
  when client hears pattern:/hello/ as msg
```
> Subscribe to an event
> ```js
> POST <slack>/subscribe/hears {
>   "endpoint": "<dest>",  // set the destination to where to publish data
>   "data": {"filter": "/hello/"}
> }
> ```
> Event is published
```js
POST <dest> {
  "objectId": "foobar",
  "event": "hears",
  "data": {
     ...
  }
}
```
```coffee
    msg reply message:'hey'
```
> ```js
> POST <slack>/reply/:objectId {
>   "message": "hey"
> }
> ```

----

```yaml
# microservice.yml
commands:
  bot:
    events:
      hears:
        arguments:
          pattern:
            type: string
        http:
          method: post
          path: /subscribe/hears
    	output:
          type: map
          commands:
            reply:
              arguments:
                message:
                  type: string
          http:
            method: post
            path: /reply/$objectId
            run:
              command: ["./server-start"]
```

</details>

<details>
<summary>Websocket</summary>

```coffee
websocket accept path:'/' as ws
```
> ```sh
> docker run -d -e OMG_ENDPOINT=platform --entrypoint ./start websocket
> ```

> Publish Event
> ```js
> POST <platform> {
>   "objectId": "foobar",
>   "event": "message",
>   "data": {
>     "message": "hello"
>   }
> }
> ```

```coffee
  when ws message as client
    client write message:'world'
```
> Pass data back to sevice
> ```js
> POST <websocket>/write/foobar {"message": "world"}
> ```

----

```yaml
# microservice.yml
commands:
  accept:
    events:
      message:
    	output:
          type: map
          commands:
            write:
              arguments:
                message:
                  type: string
              http:
                method: post
                path: /write/$objectId
    run:
      command: ["./start"]
```

</details>

----

This feature defines **stateful object integrity** between service and platform. The new `events` node provided one more level depth of command structure which enables services to be more complex in their operations.

<details>
<summary>More details here...</summary>

Start with the Slack Bot's [microservice.yml](https://github.com/microservice/slack/blob/master/microservice.yml)

Run the microservice
```sh
$ omg exec -e TOKEN=<secret> -c bot
✔ Built Docker image
✔ Ran command: `bot`
/ Service is running. Subscribe to events with `$ omg subscribe`
```

In a new terminal window subscribe to an event.
```sh
$ omg subscribe -e hears -a "filter=/^hello/"
✔ Subscribed.
/ Waiting for event...
```

In Slack simply enter a message in the general channel.

```sh
hello world
```

```sh
...
✔ Received event with data {"text": "hello world", ...}
/ Waiting for event...
```

</details>

# Objectives

#### Arguments
- `-e EVENT` event name to subscribe to (`enum`)
  - MUST be an event in the `microservice.yml` for the command being executed
- `-a NAME=VALUE` arguments according to the `microservice.yml`

#### Action

1. Create a webserver to receive events 
  - Assumed `localhost:3001` below
2. Get the destination to subscribe events from the `microservice.yml`
  - Assumed `http://microservice/sub`

```sh
POST http://microservice/sub {
  "endpoint": "http://localhost:3001",
  "id": "<unique to this subscription>",
  "event": "foobar",
  "data": {
    "key": "value"
  }
}
```

The service now is published to the event `foobar` with the `data`.

The webserver (created above) will now wait for events and log them to the screen.

### `$ omg exec`

The `exec` command needs to determine if there are `events` for this command and behave accordingly.

Similar to streaming behaviour, the command will wait for new subscriptions to be submitted.

### Additionally

`commands.$.output` MUST be omitted since there is no output for executing the service.
