### ISSUE TITLE
Environment variables in docker exec

### ISSUE THREAD

**Issue by stevepeak** [microservices/omg-cli#88]
When the `lifecycle.startup.command` has environment variables it fails to run the container:

```yaml
lifecycle:
  startup:
    command: ["FOO=bar", "echo", "$FOO"]
```
